#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt clobber

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export ANDROID_SDK="${HOME}/Library/Android" 
[ -d "$ANDROID_SDK" ] && export PATH="$ANDROID_SDK/sdk/tools:$ANDROID_SDK/sdk/platform-tools:${PATH}"

# Make android monitor work
export ANDROID_HVPROTO=ddm
